/home/suryatejadev/miniconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "main.py", line 66, in <module>
    main(args.config)
  File "main.py", line 52, in main
    model.train(datagen_train, datagen_val, exp_dir, **config['train'])
  File "../disease_forecast/engine.py", line 134, in train
    y_pred = self.predict(x_train_batch)
  File "../disease_forecast/engine.py", line 120, in predict
    ypred = self.model_task.forward(x_forecast)
  File "../disease_forecast/models/task.py", line 16, in forward
    x = self.dp(nn.BatchNorm1d(400)(x))
  File "/home/suryatejadev/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/suryatejadev/.local/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 66, in forward
    exponential_average_factor, self.eps)
  File "/home/suryatejadev/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 1254, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: running_mean should contain 200 elements not 400

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

